# We use github actions to test the code on windows and linux amd64. Circleci is used for linux arm64.

name: datadog-go
on:
  pull_request:

jobs:
  native:
    strategy:
      matrix:
        go-version:
          - 1.13
          - 1.14
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
          - "1.20"
          - 1.21
          - 1.22
          - 1.23
          - 1.24
          - 1.25
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          # These fail on macOS because of this bug https://github.com/golang/go/issues/49138
          - runs-on: macos-latest
            go-version: 1.13
          - runs-on: macos-latest
            go-version: 1.14
          - runs-on: macos-latest
            go-version: 1.15
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: go vet ./statsd/...
      - run: go fmt ./statsd/...
      - run: go test -race -v ./statsd/...

  go_12_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: stable
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: go install golang.org/dl/go1.12@latest
      - run: go1.12 download
      - run: go1.12 version
      - run: go1.12 test -v ./example/...
